-- v3 Schema Additions

-- 1. Notifications
CREATE TABLE public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  message text not null,
  type text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own notifications" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own notifications" ON public.notifications FOR UPDATE USING (auth.uid() = user_id);

-- 2. Chat Messages
CREATE TABLE public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users not null,
  receiver_id uuid references auth.users not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their messages" ON public.messages FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id);
CREATE POLICY "Users can send messages" ON public.messages FOR INSERT WITH CHECK (auth.uid() = sender_id);

-- 3. Inbox Documents
CREATE TABLE public.inbox_documents (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  sender text not null,
  subject text not null,
  type text not null, -- PDF, REPORT, CONTRACT
  requires_signature boolean default false,
  is_signed boolean default false,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.inbox_documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own documents" ON public.inbox_documents FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can sign own documents" ON public.inbox_documents FOR UPDATE USING (auth.uid() = user_id);

-- 4. Time-Off Requests
CREATE TABLE public.time_off_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  start_date date not null,
  end_date date not null,
  reason text not null,
  type text not null,
  status text default 'Pending', -- Pending, Approved, Rejected
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.time_off_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own requests" ON public.time_off_requests FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Owners and Admins can view all requests" ON public.time_off_requests FOR SELECT USING (
  auth.uid() IN (SELECT id FROM public.profiles WHERE role IN ('owner', 'admin', 'supervisor'))
);
CREATE POLICY "Users can create requests" ON public.time_off_requests FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Management can update requests" ON public.time_off_requests FOR UPDATE USING (
  auth.uid() IN (SELECT id FROM public.profiles WHERE role IN ('owner', 'admin', 'supervisor'))
);

-- 5. Audit Logs
CREATE TABLE public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users, -- can be null for system actions
  user_name text not null,
  action text not null,
  target text not null,
  type text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Only management can view audit logs" ON public.audit_logs FOR SELECT USING (
  auth.uid() IN (SELECT id FROM public.profiles WHERE role IN ('owner', 'admin'))
);
CREATE POLICY "Anyone can insert audit logs" ON public.audit_logs FOR INSERT WITH CHECK (true);

-- 6. Knowledge Base
CREATE TABLE public.knowledge_base (
  id bigint generated by default as identity primary key,
  folder text not null,
  title text not null,
  content text not null,
  access_level text default 'Everyone',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.knowledge_base ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can view KB" ON public.knowledge_base FOR SELECT USING (true);
CREATE POLICY "Only management can edit KB" ON public.knowledge_base FOR ALL USING (
  auth.uid() IN (SELECT id FROM public.profiles WHERE role IN ('owner', 'admin', 'supervisor'))
);
