-- CX Cases seed from Customer Tracker Sheet (May 2026)
-- Run once in Supabase SQL Editor. Safe to run only once — no dedup guard.

INSERT INTO public.cx_cases
  (customer_name, phone, pipeline_stage, priority, status, issue, action_taken, customer_words, lab_notes, payment_left, pay_status)
VALUES

('Anthony Camara','6038570010','IMP KIT DEL','HIGH','New CX',
 'He got his second remake and he doesnt like it at all',
 'Left him a voice mail, sent a sms. 05/08/2026: Left a vm // 05/10/2026: texted him the TC.',
 'Sending new imp kit on us for the CX service mistakes we did and I will personally follow up with him myself, try to forward him to MIKE',
 'Mr. Ahmed got her back on track',200.00,'Defaulted'),

('Sammy Wright','7692479340','IMP KIT DEL','MEDIUM','Took action & CX answered',
 'He need someone to help him take impression kit',
 'Called no answer left a message, schedule an appointment on saturday May 9th on 10:30 am.',
 'I''m leaving out Saturday night I''ll be home Sunday night I''ll give you a call first thing Monday morning',
 'Took impressions and waiting it to be delivered to PO',166.65,'Paid'),

('Daisey Grandberry','9803013186','IMP KIT DEL','HIGH','Take action',
 'Impression taking for a Remake',
 'Call no answer left VM and sms',
 'please contact me after mothers day or I want all money back so I can go get my teeth',
 'She received a kit on April 29, She needs follow up',143.31,'Paid'),

('Shirley Jules','3477841546','IMP KIT SENT','LOW','No action taken',
 'IMP KIT sent ETA: awaiting for CX pick up',
 'Mike Sent to Store / TC waiting to send it for me. Need to set up an appointment on May 7th. 05/11/2026: called the store and received the kit, left a text updating her. 05/12/2026: received imp kit was awful and need a new imp kit left a text.',
 'She paid $75 next payment is $225',
 'New Kit is sent',NULL,'Paid'),

('Danielle Leger','303743684','VENEERS DEL','HIGH','Veneers delivered',
 'She doesnt like her veneers very disappointment - SHE RECEIVED ON APRIL 30TH',
 'Called no answer left a vm and sms // 05/10/2026: She texted us on may 7th said she wants a refund. 05/11/2026: called no answer left a text requesting pictures from her and trying to understand her concern.',
 'No definition it looks like a piece of plastic. Pretty big gap between the veneers and the front tooth.',
 'Paid remake in the lab - Remake in the Lab 5/12/2026',NULL,'Disputed'),

('Brook Mitchelle','2543016970','IN PRODUCTION','HIGH','Veneers delivered',
 'NO PAY - remake the imp kit cause she didnt like current veneers and we dont have her imp in labs',
 '05/10/2026: left a text. 05/11/2026: she texted back thanks for reaching out and disappeared so I left a text to assist her with her concern.',
 'Paid in full on the website - RISK OF DISPUTE',
 'Good impressions. She sent pics of 2 top impressions - the left one is good while the right one is bad, we need her to send the left one. She did take her impressions but didnt send them to us.',
 NULL,'Disputed'),

('Carlos Rodriguez','7322130071','VENEERS DEL','HIGH','Delivered & interested',
 'Needs a call - not happy with his veneers',
 'Left a text on may 3rd no answer. Left another text on may 10th. 05/10/2026: he answered my text and will try to schedule an appointment for tomorrow to fix his issue.',
 'He thinks we are a fraud',
 'His impressions was terrible, he used to contact us on FB but there was delayed reply from our side and received bad impressions so he needs new impressions',
 299.99,'Paid'),

('Shawna Hardy','7576906415','VENEERS DEL','LOW','Charged, expecting a call',
 'She doesnt like her veneers very disappointment - SHE RECEIVED ON APRIL 16TH',
 'She emailed us on apr 30th and happy with her veneers',
 NULL,
 'She is a returning happy customer, everything is perfect with her now',
 NULL,'Paid'),

('Stephanie Sands','3058798948','VENEERS DEL','MEDIUM','Failed money',
 'She Needs dental adhesive because veneers are falling. 05/07/2026: Sands complains the teeth are too bulky and needs to be flatter, they do not fit. Generated a claim #2457980.',
 '05/11/2026: she said it is too bulky and she is very frustrated with the veneers I told her to send some pictures and the doctor advised to send a new kit.',
 NULL,
 'Customer still not happy with the veneers - mentioning it is bulky. We need pics to check if we do thinner veneers or need new impressions.',
 299.99,'Paid'),

('Theron Blackburn','9182913158','Remake','LOW','Took action & CX answered',
 'Needs a follow up for the colour',
 'Called no answer left a vm and sms. Replied over the sms and will create a lab claim and set an appointment. Schedule on may 5th tuesday at 10:30 am. 05/07/2026: Called no answer left SMS. 05/10/2026: left another text. no answer.',
 NULL,
 'Customer needs more Darker shade veneers',375.00,'Defaulted'),

('James Bridges','5167106672','VENEERS DEL','LOW','Took action & CX answered',
 'Complaint - needs a follow up. 05/07/2026: Called, the veneers fit but it is cracked. Can start with the remake.',
 '05/10/2026: left him a SMS to tell him the remake is in production and please pay the balance.',
 NULL,
 'He is happy with the veneers but he is having a crack. We can remake him but he has to finish his balance.',
 193.31,'Paid'),

('Wanda Franklin','2172486820','VENEERS DEL','MEDIUM','Needs Refund',
 'She didn''t like the veneers at all and wants a refund',
 '05/10/2026: left SMS',
 'She paid $310, balance $219. She contacted the bank and said do not let PV take money out of the bank.',
 'Awful impressions so veneers were not good. If she wants new veneers she needs new impressions.',
 219.00,'Needs Refund'),

('Elizabeth Cotton','14174393470','Remake','MEDIUM','No action taken',
 'Fits good but dont like the color on april 29. She wants them to glow - just needs a super glow white smile',
 'Left vm and sms',
 'Call me whenever we get the claim status',
 'Wasnt a bright color - in lab fabrication',NULL,'Paid'),

('Emma Viel','4044379910','VENEERS DEL','MEDIUM','Take action',
 'Someone stole her veneers but it shows delivered on the TC',
 'Send sms no answer',
 NULL,
 'Recommend remaking new veneers but with new impressions',329.99,'Paid'),

('Tabitha Thurston','7404059931','IMP KIT DEL','HIGH','Take action',
 'She received the second kit - she needs help taking the IMP',
 'No answer send sms. 05/11/2026: left SMS',
 NULL,
 'Not good impressions in the first time',137.12,'Paid'),

('Berneta Stone','9017058266','VENEERS DEL','MEDIUM','Take action',
 'Veneers do not fit right - Follow back call. 05/11/2026: cx replied to previous message "yes sir" left another SMS requesting more clarification about her concern.',
 NULL,NULL,
 'Stopped here',202.49,'Defaulted'),

('Evonnie Bolton','13012049939','VENEERS DEL','LOW','Take action',
 'No follow up - cx issue',
 'Called and sent SMS to make it right for her',
 'She paid $300 down payment and disputed $460',
 'We got our dispute money back. Will still call her and align her.',
 NULL,'Disputed'),

('Melvin Brooks','12109943508','VENEERS DEL','LOW','Took action & CX answered',
 'Can''t Close his Mouth fully, needs follow up',
 'Called and he said the remake fits better',
 NULL,
 'He says he cant close his mouth but we made new veneers and shipped it to him',
 279.00,'Paid'),

('Tamika Williams','17627160495','VENEERS DEL','LOW','Take action',
 'She is very disappointed about her veneers',
 NULL,NULL,
 'Awful impressions = bad veneers',125.00,'Disputed'),

('Barbara Inglit','17063067949','VENEERS DEL','MEDIUM','Took action & CX answered',
 'She ordered for her son who has issues with the bottom veneers (son name: John)',
 'She is very happy we called her. Waiting on her son''s veneers picture to make him a new one or send him a new kit.',
 'Little bit shorter and not as thick',
 'Remake top and bottom - they hurt gums need them shorter. Will collect payment.',
 331.31,'Defaulted'),

('Kathy Reed','18433447340','IMP KIT DEL','HIGH','Take action',
 'Needs a follow up for imp kit',
 'Called no answer left SMS',
 NULL,
 'She needs help with the impression. Spoke with her and she will contact us on monday.',
 299.99,'Defaulted'),

('Debbie Lemon','16124076447','VENEERS DEL','HIGH','Take action',
 'Needs a follow up - she is very disappointed with the veneers and the colour',
 'Left a vm NO ANSWER',
 NULL,
 'We can remake with more normal white color but she needs to pay and send us pics of current veneers. No answer.',
 279.00,'Defaulted'),

('Jerdaine West','19432820107','VENEERS DEL','HIGH','Take action',
 'Issue with his veneers - he didnt like it. Needs a follow up',
 'No answer Left SMS',
 NULL,
 'Very bad impressions need new impressions if she needs a remake',289.99,'Defaulted'),

('Myrtle Faitala','15625440476','PAYMENT RECIEVED','HIGH','Take action',
 'She Needs a follow up - Refund ASAP',
 'Refunded. 05/11/2026: left a text.',
 NULL,
 'Just received the kit and sent it back unopened. Her plan is active on partially and paying money.',
 289.99,'Needs Refund'),

('Burton Mancey','18435172711','VENEERS DEL','MEDIUM','Take action',
 'He Needs a refund - we took the full amount and now he wants refund. He disputed the whole amount and won it. NEEDS A FOLLOW UP CALL VENEERS ISSUE',
 NULL,NULL,
 'He stopped replying after he received the veneers. Waiting for dispute money to be back - then he will reorder with us because he wants the veneers.',
 NULL,'Disputed'),

('Rochelle Lewis','12024005713','IMP KIT DEL','HIGH','Take action',
 'Needs a follow up for imp kit appointment',
 'Left a VM no answer / left SMS',
 NULL,
 'She stopped answering after she received the kit',499.99,'Defaulted'),

('Otis Jackson','13523307571','IMP KIT DEL','HIGH','Take action',
 'Needs follow up for impression taking',
 'Left a VM no answer / left SMS',
 NULL,
 'She stopped answering after she received the kit',249.99,'Paid'),

('Isabella Thomas','16012138154','IMP KIT DEL','HIGH','Take action',
 'She needs a new IMP KIT AND AN IMMEDIATE FOLLOW UP',
 '05/11/2026: left a SMS',
 NULL,
 'She needs follow up with imp - called no answer',166.65,'Defaulted'),

('Patrick Hogan','18328851824','VENEERS DEL','MEDIUM','Take action',
 'Returning cx was not happy about the veneers - has issues with the veneers',
 '05/11/2026: left SMS NO ANSWER',
 NULL,
 'He is a returning happy customer but it looks like he stopped replying after taking the veneers',
 249.99,'Defaulted'),

('Rose Conteh','12052033421','VENEERS DEL','HIGH','Take action',
 'She Needs Follow up ASAP - Frustrated with the veneers',
 '05/11/2026: LEFT SMS',
 NULL,
 'Awful impressions',140.99,'Disputed'),

('Shayretta Spikes','13345301327','IN PRODUCTION','LOW','Took action & CX answered',
 'She needs a follow up with her and collect another payment. SENT TODAY - She will send the imp kit, appointment is done and she paid.',
 'Called she answered the kit will be delivered tomorrow. Will give her a call tomorrow between 10:30am-2:30pm.',
 NULL,'New',137.00,'Paid'),

('Trevon McAllman','12513012153','IN PRODUCTION','MEDIUM','Take action',
 'He Needs a follow up for update / Needs a follow up ASAP',
 '05/11/2026: left SMS',
 'He paid $150 balance of $449.99',
 'Still in lab - pause the production of his veneers until next week. If he makes a payment, then we can continue. If he doesn''t, then we will not continue because it looks like he''s having a lot of financial issues.',
 449.99,'Defaulted'),

('Marsha Tabron','16306991620','IMP KIT DEL','HIGH','Take action',
 'She has a REMAKE in production needs a follow up ASAP. She paid extra $30 twice we need to video call her and help her to take the impression',
 '05/11/2026: left SMS',
 NULL,'We sent new kit',109.99,'Paid'),

('Robert Fisher','13143058640','IMP KIT DEL','HIGH','Take action',
 'He thinks the IMP KIT IS NOT PREMIUM - NEEDS TO CALL AND UNDERSTAND WHAT IS GOING ON',
 '05/11/2026: left SMS',
 NULL,'Never received his impressions',569.99,'Defaulted'),

('John Holmes','12246364601','IMP KIT DEL','HIGH','Take action',
 'Needs a follow up - been trying to reach him and no answer. His payment plan still active and need to get in touch asap.',
 '05/11/2026: left SMS',
 NULL,'Disappeared after receiving the kit',165.70,'Paid'),

('Michael Brown','12282717448','IMP KIT DEL','HIGH','Take action',
 'Got the IMP KIT no answer - Needs Follow up for his IMP KIT. HE RECEIVED HIS 2ND IMP KIT ON FEB 19TH',
 '05/11/2026: left SMS',
 NULL,'Disappeared after receiving the kit',549.99,'Defaulted'),

('Elaine Monteaux','19362685989','IMP KIT DEL','HIGH','Take action',
 'She received her kit and she is trying to cancel her order but we spoke with her and made her continue with her order. Needs a call ASAP',
 '05/11/2026: left SMS',
 NULL,'Disappeared after receiving the kit',343.99,'Defaulted'),

('Brittany Billings','18703954197','IMP KIT DEL','HIGH','Took action & CX answered',
 'She needs a follow up for IMP taking',
 '05/11/2026: CX texted us on may 6th no answer, left her SMS today. She replied to the text and asked about how to take pictures. We are waiting on the impression and pictures so we can proceed with production. She sent us the impression picture for approval.',
 NULL,
 'Communicating now - waiting on impression to arrive',269.98,'Paid'),

('Lillie Williams','19082652435','VENEERS DEL','HIGH','Take action',
 'She is having problem with her veneers requesting a remake / Follow up',
 '05/11/2026: left SMS',
 NULL,
 'No teeth in the top so needs denture adhesive and very bad impression in the bottom that needs remake',
 482.29,'Paid'),

('Holly Wilkins','12812037705','VENEERS DEL','HIGH','Took action & CX answered',
 'She is a returning customer - she received her veneers on feb/03 / Just a quick follow up',
 '05/11/2026: left SMS, she answered and we will talk tomorrow.',
 NULL,'All good',NULL,'Paid'),

('Bobby Brown','18722144114','IMP KIT DEL','HIGH','Take action',
 'We can call him and check on him for the impression and get him back',
 '05/11/2026: left SMS',
 NULL,'Disappeared after receiving the kit',NULL,'Defaulted'),

('Shanice Davis','18642378516','VENEERS DEL','HIGH','Take action',
 'Needs a follow UP - Veneers are so big for her mouth she cant wear them',
 '05/11/2026: left SMS',
 NULL,'We can remake her but she has to pay',549.99,'Defaulted'),

('James Harris','18597058549','IMP KIT DEL','HIGH','Take action',
 'Needs a follow up for his IMP KIT',
 '05/11/2026: left SMS',
 NULL,'Disappeared after receiving the kit',499.99,'Defaulted'),

('Linda Waile','19548682899','VENEERS DEL','HIGH','Take action',
 'She has an issue with her veneers Needs a follow up - weird message on crm, can''t reach her',
 NULL,NULL,
 'No teeth top and bottom - she needs denture adhesive',481.24,'Defaulted'),

('Lindsay Skidmore','14697337461','VENEERS DEL','HIGH','Take action',
 'She received the veneers and need a follow up - she is having issue with the product',
 'Left SMS. 05/11/2026: left SMS',
 NULL,
 'Her veneers are good we need to know why she is not happy - need teeth pics',
 NULL,'Paid'),

('Kwamy Corsy','15186063090','IN PRODUCTION','HIGH','Took action & CX answered',
 'Needs a follow up for IMP KIT. SENT TODAY - Answered the call / booked an appointment on friday 10am to 12pm.',
 '05/08/2026: Made the imp together - there was a small mistake in the impression. I aligned him that there could be human error with their veneers but we will be able to fix it. He is fine with it and doesnt want to do another imp kit.',
 NULL,'New - Kit sent',NULL,'Paid'),

('Debra Franklin','19366611285','IMP KIT DEL','MEDIUM','No action taken',
 'She needs IMP KIT helping',
 'Sent SMS. Dentist work in place - debra will call us for her impression, do not call until she calls.',
 NULL,'Need new impressions',166.63,'Paid'),

('Patricia Mark','13372518053','IMP KIT DEL','HIGH','Take action',
 'She needs a follow UP for imp kit taking - she is very Upset. She received the kit on Apr.28th',
 'Sent SMS',
 NULL,'Need impressions',333.31,'Paid'),

('Stacy Boatwright','18034806380','VENEERS DEL','LOW','Charged, expecting a call',
 'She has no complaints and she is happy - Needs a follow up but not urgent',
 NULL,NULL,'Happy customer',NULL,'Paid'),

('Vanessa Strong','14147327475','VENEERS DEL','HIGH','Take action',
 'She needs a denture adhesive she doesnt have top teeth. She got a remake. Needs a call about her teeth. WE CAN TRY THE FEEDBACK ON THE DENTURE PROGRAM',
 'Left a SMS',
 NULL,NULL,250.98,'Paid'),

('Peggy Potts','17312254988','IMP KIT DEL','HIGH','New CX',
 'She disputed - the veneers were not delivered in the right place. She didnt receive the kit - ordered a new kit for her. She will decide if she wants to continue and pay her dues. Forward her to Mike (Mr. Ahmed). Qualified for free denture adhesive.',
 '05/10/2026: left a shipping update text. 05/11/2026: left a text - she should receive the imp kit tomorrow.',
 NULL,'Mr. Ahmed got her back on Track',NULL,'Disputed'),

-- PAGE 2

('Maria Modica','16165108279','VENEERS DEL','HIGH','Took action & CX answered',
 'Needs a follow up - Issue with the veneers.',
 'Left an SMS to establish positive communications. No answer yet.',
 NULL,
 'She is happy with the veneers and wrote a positive review on the website',
 171.99,'Paid'),

('Sandra Thompson','17085674309','IMP KIT DEL','HIGH','Take action',
 'She paid $50 for the impression kit - delivered on April 18. She can pay her first payment on the 3rd of May and needs help doing her impression kits.',
 'Collect first payment. Help her with imp kit. No answer sent SMS.',
 NULL,'Need impression follow up',549.99,'Paid'),

('Gabriel Williams','19708969406','VENEERS DEL','HIGH','Take action',
 'Gabriella got his veneers on May 1st - need to follow up with him to see how he feels with his new veneers.',
 '05/11/2026: left SMS',
 NULL,'Follow up if he is happy or not',NULL,'Paid'),

('Rose Noboru','17019895558','VENEERS DEL','HIGH','Take action',
 'Needs a follow up with a veneers issue - her veneers are so big can''t close her mouth',
 'Sent SMS reminding her of the PICS',
 NULL,'Very bad impressions - if remake we need new imp',NULL,'Paid'),

('Mamie Andrews','19737660197','IMP KIT DEL','HIGH','Take action',
 'Needs a follow up - she received IMP KIT on Jan 24th.',
 'Sent a text message for appointment set up',
 NULL,'Disappeared after receiving imp',517.00,'Defaulted'),

('Tatsy Fulmer','18032588828','VENEERS DEL','HIGH','Take action',
 'She is requesting a remake for the top - the bottom is good. Needs a follow up.',
 'Sent a text reminding her to send us her veneers pics so we can initiate the remake',
 NULL,'Need new impressions',99.00,'Paid'),

('Virginia Guzman','12629602063','VENEERS DEL','HIGH','Take action',
 'She received her veneers on march 4th - they werent fitting and needs a remake',
 'No answer left SMS',
 NULL,'Awful impressions - need new impressions',319.99,'Defaulted'),

('Shirley Robinson','19123098932','IMP KIT DEL','HIGH','Take action',
 'Another imp kit sent for a new remake ON april 20th / needs a follow up for Imp taking',
 'Called no answer Left SMS. 05/14/2026: left sms',
 NULL,'Follow up if happy or not',299.00,'Paid'),

('Cindy Grant','13472280262','VENEERS DEL','HIGH','Took action & CX answered',
 'She is so disappointed - no Follow up with her but we still can call her. Veneers delivery issue.',
 'Called no answer and sent SMS. 05/11/2026: Cx answered on may 7th no follow up from us and I left SMS today. She answered and wants a call on thursday 05/14/2026.',
 NULL,
 'She needed remake - there was an issue with customer service and she made a dispute',
 130.00,'Disputed'),

('Linda Waile','19102920185','VENEERS DEL','HIGH','Take action',
 'She had an issue with the veneers - Qualified for dentures program.',
 NULL,NULL,NULL,481.24,'Defaulted'),

('Clifton Holbrook','13148535827','VENEERS DEL','HIGH','Take action',
 'Qualified for a dentures and he needs a refund',
 'Called no answer left SMS. 05/11/2026: left SMS NO ANSWER',
 NULL,NULL,182.00,'Disputed'),

('Marjorie Jackson','14199755922','Interested CX','HIGH','Delivered & interested',
 'UNCLOSED SALE (INTERESTED)',
 NULL,NULL,NULL,NULL,NULL),

('Terry Mathews','12027658398','VENEERS DEL','HIGH','Take action',
 'Needs a follow up on her veneers',
 'Called and left SMS',
 NULL,
 'Good impressions - if he needs a remake we need pics to see the issue',
 NULL,'Paid'),

('James Barnes','14238345929','VENEERS DEL','HIGH','Take action',
 'He has issue with the veneers - bottom is hitting when trying to close his mouth. He is not happy with his veneers. Paid in full. Needs a follow up.',
 'He called and left a VM. I called no answer and left him SMS.',
 'He was not happy with the veneers at all because they hurt his top teeth and are sharp in the back. His gums are also very badly irritated. He requested a refund but we explained we cannot issue one. He said if we proceed with a remake or dentures he wants to be satisfied with what he paid for. We will likely proceed with the remake.',
 'Remake in progress',NULL,'Paid'),

('Stephanie Bell','19013035633','VENEERS DEL','HIGH','Take action',
 'She got 2 remakes and didnt like it',
 NULL,NULL,NULL,NULL,'Disputed'),

('Tiara Joyner','13016744200','VENEERS DEL','HIGH','Take action',
 'Bad veneers and bad CX service',
 NULL,
 'She didnt send us pics of the veneers - her dispute is still active we can contact her to see the issue',
 NULL,NULL,'Paid'),

('Elizabeth Brunson','18036058769','IMP KIT DEL','HIGH','Take action',
 'She is still on the IMP KIT status - Needs a follow up Call.',
 '05/11/2026: left SMS',
 NULL,'Disappeared after receiving an impression kit',519.99,'Defaulted'),

('Beatriz Rosado','14753124120','VENEERS DEL','HIGH','Take action',
 'Needs a FOLLOW UP - she threw it away. She wanted gold star on her veneers but she didnt get it.',
 NULL,NULL,
 'We can remake her - lets contact the customer',115.99,'Paid'),

('Shirley Martin','16014191516','VENEERS DEL','HIGH','Take action',
 'She didnt like her veneers - bottom are too big and not long enough to cover her veneers. She sent pictures on the crm.',
 'They both don''t fit and they are too bulky. Need the doctor to listen to the crm last call to understand her case. I told her to pay today. 05/08/2026: called no answer left SMS.',
 NULL,
 'Easy issue to be fixed - if she needs a remake lets inform the lab but we need her to pay.',
 349.99,'Paid'),

('Mike Wedinger','19415446087','VENEERS DEL','HIGH','Charged, expecting a call',
 'He likes the veneers 95% but it needs a dental adhesive because it keeps on popping out - Needs a follow up',
 NULL,NULL,'Great',NULL,'Paid'),

('Sandra Goodson','13343122074','VENEERS DEL','HIGH','Take action',
 'She received veneers, she liked the veneers but the upper part is a bit loose - advised to apply dental adhesive',
 'Called on 05/07/2026 - the bottom fit good the top do not fit at all. Give her a call back in 2 hours.',
 NULL,
 'She needs denture adhesive as she is not having any teeth in the top at all',
 507.25,'Defaulted'),

('Jesse Clay','13235667373','VENEERS DEL','HIGH','Take action',
 'Needs a follow up with his veneers - call tomorrow 3 o''clock. 05/13/2026: left a text.',
 NULL,NULL,
 'No teeth at all - we need to follow her up',358.32,'Paid'),

('Delphene Woody','18642450827','VENEERS DEL','HIGH','Take action',
 'Needs a follow up with his veneers - they do not fit.',
 'Called no answer left SMS',NULL,
 'She has no teeth at all',179.00,'Defaulted'),

('Marisa Parson','13187899615','VENEERS DEL','HIGH','Take action',
 'She doesn''t like them and she just wants to send them back because they don''t fit right.',
 'Sent SMS',NULL,
 'Awful impressions - if he needs new veneers we need new imp. Sent an email to get her back.',
 261.74,'Defaulted'),

('Geraldine Griego','15755454087','VENEERS DEL','HIGH','Charged, expecting a call',
 'His veneers arrived and we just need to follow up to see how he''s doing with them.',
 NULL,NULL,
 'He is a returning customer - probably he is okay',NULL,'Paid'),

('David Balfour','13137183938','VENEERS DEL','HIGH','Take action',
 'Been following up no answer - on march 31 called and he refused to pay and asked for photos but no answer. Needs a follow up.',
 'Called no answer left a SMS',NULL,
 'Disappeared after having the veneers - Email is not correct, Needs a phone call',499.99,'Defaulted'),

('Sandra Nieves','17169128235','VENEERS DEL','HIGH','Take action',
 'Veneers delivered but she thinks we are fraud',
 'Called no answer',NULL,
 'Bad impressions = bad veneers',518.17,'Disputed'),

('Larry Mickelson','19707790315','VENEERS DEL','HIGH','Delivered & interested',
 'Needs a call back - he disputed but he is interested to do the bottom as well - just align him',
 'Called no answer, Send him SMS',NULL,
 'He is a returning customer on stripe. The dispute cause is that he didn''t make the payment himself probably.',
 NULL,'Disputed'),

('Martha','17024173292','VENEERS DEL','HIGH','Take action',
 'Stolen card. She doesn''t want to have any more conversation. She thinks they''re plastic and she doesn''t like the way they look at all. She is not happy.',
 NULL,NULL,NULL,NULL,'Paid'),

('Bridget Francis','16786838803','IMP KIT DEL','HIGH','Take action',
 'After the customer''s impression kit was approved by the doctor, she received another impression kit a month later instead of the veneers she was expecting. She had hoped to receive her veneers early so she could have them for her birthday.',
 NULL,NULL,NULL,549.99,'Disputed'),

('Curtis Shepherd','19014121519','VENEERS DEL','HIGH','Take action',
 'Issues with the veneers, but customer did not send any photos and did not answer.',
 'Called no answer tried to charge him insufficient funds left him SMS',NULL,
 'Bad imp if need remake need new impressions. Sent him an email to get him back on track.',
 124.98,'Paid'),

('Willie Jones','13128356009','VENEERS DEL','HIGH','Charged, expecting a call',
 'No Issue',
 NULL,NULL,'Very bad impressions',NULL,'Paid'),

('Rwanda Lindsey','16014988003','VENEERS DEL','HIGH','Take action',
 'No answer needs a follow up - Veneers do not fit',
 'Called no answer on 05/07/2026.',NULL,
 'Disappeared - I sent an email trying to get her back on track',NULL,'Paid'),

('George Salcedo','17183167113','VENEERS DEL','HIGH','Charged, expecting a call',
 'Order completed no issues - needs a call to check on him and collect payments. He stopped paying since february.',
 'No answer send sms, tried to charge insufficient funds',NULL,
 'Happy with the veneers',NULL,'Paid'),

('Betty Saxon','17062716825','VENEERS DEL','HIGH','Charged, expecting a call',
 'Happy with her veneers and her plan is still active on partially - She is paying she is fine',
 NULL,NULL,NULL,249.00,'Paid'),

('Marjorie Newman','18604616077','PAYMENT RECIEVED','HIGH','Take action',
 'Paid on the CRM $30 to get a new impression kit and a new remake, but she never sent us the photos of what she did not like about the veneers. We are still waiting on those photos.',
 'Left a vm NO ANSWER / sent SMS',
 NULL,NULL,NULL,'Paid'),

('John Poplawski','12699268261','VENEERS DEL','LOW','Charged, expecting a call',
 'Veneers Del needs a check up',
 NULL,NULL,NULL,171.00,'Paid'),

('Uravashi B','6264100945','VENEERS DEL','MEDIUM','Took action & CX answered',
 'CX called on 05/07/2026 she said it fits it is just bulky - needs it to be thinner, waiting for pictures today. 05/08/2026: Sent a text to remind her to send pics.',
 'If the front 6 teeth can be made small in size in both width and length then it would be great',
 NULL,'Remake',NULL,'Paid'),

('Jaray Grant','2058076848','IMP KIT DEL','LOW','New CX',
 'Returning Customer just placed new order and need a kit - paid full on the CRM',
 NULL,NULL,NULL,NULL,'Paid'),

('Janise Man-son-hing','8133102390','IN PRODUCTION','LOW','Took action & CX answered',
 'Address: 16740 WHIRLY ROAD, LUTZ, FLORIDA, 33558. She is leaving the country on JUNE 14TH. NATURAL WHITE, NO MISSING TEETH, ONE CROWN. She is very interested - wants full set for $499 + $50 delivery before june 5th.',
 '05/08/2026: gave her a follow up call after we sent the email yesterday and left SMS. 05/11/2026: called her and resent the email - wants to get the full set for $499 and $50 extra fees for delivery before june 5th.',
 NULL,'Imp in the lab',NULL,'Paid'),

('James Gordon','7606016734','Interested CX','LOW','Delivered & interested',
 '',NULL,NULL,NULL,NULL,NULL),

('Jakeevia Lane','4047252511','PAYMENT RECIEVED','LOW','New CX',
 'New Order Paid on Full',
 NULL,NULL,NULL,NULL,'Paid'),

('Sura Ragonandan','6076010564','Interested CX','LOW','Delivered & interested',
 '05/10/2026: Texted her to check up and see her availability for a call.',
 NULL,NULL,NULL,NULL,NULL),

('Johnathan Johnson','2292207657','IN PRODUCTION','LOW','Took action & CX answered',
 '05/14/2026: He is a returning CX we have his impressions and he needs full set SUPER WHITE.',
 '05/14/2026: Paid $299.50 and he will pay $299.50 once we finish the veneers',
 NULL,NULL,299.50,'Paid');
