'use client';

import { useState, useRef } from 'react';
import { dbOp } from '@/utils/db';

const DEFAULTS = {
  company_name: 'Pioneers Veneers',
  tagline: 'Excellence in Every Smile',
  primary_color: '#4f46e5',
  footer_text: 'This document was generated by the Pioneers Veneers Enterprise Platform. It is legally binding upon physical signature.',
  logo_base64: '',
  apply_payslips: true,
  apply_contracts: true,
  apply_reports: true,
};

export default function DesignClient({ initialSettings }: { initialSettings: any }) {
  const s = initialSettings ?? {};
  const [companyName, setCompanyName] = useState(s.company_name ?? DEFAULTS.company_name);
  const [tagline, setTagline] = useState(s.tagline ?? DEFAULTS.tagline);
  const [color, setColor] = useState(s.primary_color ?? DEFAULTS.primary_color);
  const [footerText, setFooterText] = useState(s.footer_text ?? DEFAULTS.footer_text);
  const [logo, setLogo] = useState<string>(s.logo_base64 ?? DEFAULTS.logo_base64);
  const [applyPayslips, setApplyPayslips] = useState(s.apply_payslips ?? DEFAULTS.apply_payslips);
  const [applyContracts, setApplyContracts] = useState(s.apply_contracts ?? DEFAULTS.apply_contracts);
  const [applyReports, setApplyReports] = useState(s.apply_reports ?? DEFAULTS.apply_reports);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState('');
  const fileRef = useRef<HTMLInputElement>(null);

  const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (file.size > 500 * 1024) { setError('Logo must be under 500 KB'); return; }
    const reader = new FileReader();
    reader.onload = (ev) => { setLogo(ev.target?.result as string); setError(''); };
    reader.readAsDataURL(file);
  };

  const handleSave = async () => {
    setSaving(true);
    setSaved(false);
    setError('');
    const payload = {
      ...(s.id ? { id: s.id } : {}),
      company_name: companyName,
      tagline,
      primary_color: color,
      footer_text: footerText,
      logo_base64: logo,
      apply_payslips: applyPayslips,
      apply_contracts: applyContracts,
      apply_reports: applyReports,
    };
    const { error: err } = await dbOp('brand_settings', 'upsert', payload);
    if (err) { setError(err); } else { setSaved(true); setTimeout(() => setSaved(false), 3000); }
    setSaving(false);
  };

  const initials = companyName.split(' ').map((w: string) => w[0]).join('').slice(0, 2).toUpperCase();

  return (
    <div className="page-fade">
      <div className="briefing" style={{ marginBottom: 20 }}>
        <div>
          <div className="card-title">PDF Templates &amp; Brand Settings</div>
          <div className="card-sub">Applied to all generated payslips, contracts, and reports</div>
        </div>
        <div className="briefing-actions">
          <button className="btn btn-acc" onClick={handleSave} disabled={saving}>
            {saving ? 'Saving…' : saved ? '✓ Saved' : 'Save Changes'}
          </button>
        </div>
      </div>

      {error && (
        <div style={{ background: 'oklch(0.97 0.03 25)', color: 'var(--err)', border: '1px solid oklch(0.90 0.06 25)', padding: '10px 14px', borderRadius: 8, fontSize: 13, marginBottom: 16 }}>
          {error}
        </div>
      )}

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, alignItems: 'flex-start' }}>
        {/* Settings panel */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div className="card" style={{ padding: '20px 18px' }}>
            <div className="card-title" style={{ marginBottom: 16 }}>Company Identity</div>

            <div className="pv-fld">
              <label>Company Logo</label>
              <input ref={fileRef} type="file" accept="image/png,image/jpeg,image/svg+xml,image/webp" style={{ display: 'none' }} onChange={handleLogoUpload} />
              <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                <div style={{ width: 56, height: 56, borderRadius: 10, border: '1.5px dashed var(--line)', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', background: 'var(--surface-2)', flexShrink: 0 }}>
                  {logo ? (
                    <img src={logo} alt="Logo" style={{ width: '100%', height: '100%', objectFit: 'contain' }} />
                  ) : (
                    <div style={{ width: 40, height: 40, borderRadius: 8, background: `linear-gradient(135deg, ${color}, ${color}cc)`, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontWeight: 700, fontSize: 14 }}>
                      {initials}
                    </div>
                  )}
                </div>
                <div>
                  <button className="btn btn-sec" onClick={() => fileRef.current?.click()}>Upload logo</button>
                  {logo && (
                    <button className="btn btn-sec" style={{ marginLeft: 6, color: 'var(--err)' }} onClick={() => setLogo('')}>Remove</button>
                  )}
                  <div style={{ fontSize: 11, color: 'var(--ink-4)', marginTop: 4 }}>PNG, JPG, SVG or WebP · Max 500 KB</div>
                </div>
              </div>
            </div>

            <div className="pv-fld">
              <label>Company Name</label>
              <input type="text" value={companyName} onChange={e => setCompanyName(e.target.value)} />
            </div>

            <div className="pv-fld">
              <label>Tagline / Subtitle</label>
              <input type="text" value={tagline} onChange={e => setTagline(e.target.value)} placeholder="e.g. Excellence in Every Smile" />
            </div>
          </div>

          <div className="card" style={{ padding: '20px 18px' }}>
            <div className="card-title" style={{ marginBottom: 16 }}>Brand Color</div>
            <div className="pv-fld">
              <label>Primary color</label>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                <input type="color" value={color} onChange={e => setColor(e.target.value)} style={{ width: 42, height: 36, border: '1px solid var(--line)', borderRadius: 6, cursor: 'pointer', padding: 2 }} />
                <input type="text" value={color} onChange={e => { const v = e.target.value; if (/^#[0-9a-fA-F]{0,6}$/.test(v)) setColor(v); }} style={{ width: 100, fontFamily: 'var(--mono)' }} maxLength={7} />
                <div style={{ display: 'flex', gap: 6 }}>
                  {['#4f46e5', '#0891b2', '#059669', '#d97706', '#dc2626', '#7c3aed'].map(c => (
                    <div key={c} onClick={() => setColor(c)} style={{ width: 22, height: 22, borderRadius: 4, background: c, cursor: 'pointer', border: color === c ? '2px solid var(--ink)' : '2px solid transparent' }} />
                  ))}
                </div>
              </div>
            </div>
          </div>

          <div className="card" style={{ padding: '20px 18px' }}>
            <div className="card-title" style={{ marginBottom: 16 }}>Document Footer</div>
            <div className="pv-fld">
              <label>Footer disclaimer text</label>
              <textarea rows={3} value={footerText} onChange={e => setFooterText(e.target.value)} placeholder="Legal disclaimer or footer notice on all generated PDFs…" />
            </div>
          </div>

          <div className="card" style={{ padding: '20px 18px' }}>
            <div className="card-title" style={{ marginBottom: 16 }}>Apply Branding To</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              {[
                { label: 'Payslips', value: applyPayslips, set: setApplyPayslips },
                { label: 'Contracts', value: applyContracts, set: setApplyContracts },
                { label: 'Reports & Warnings', value: applyReports, set: setApplyReports },
              ].map(({ label, value, set }) => (
                <label key={label} style={{ display: 'flex', alignItems: 'center', gap: 10, fontSize: 13, cursor: 'pointer', userSelect: 'none' }}>
                  <div
                    onClick={() => set(!value)}
                    style={{ width: 36, height: 20, borderRadius: 10, background: value ? 'var(--accent)' : 'var(--line)', position: 'relative', transition: 'background 0.2s', cursor: 'pointer', flexShrink: 0 }}>
                    <div style={{ position: 'absolute', top: 2, left: value ? 18 : 2, width: 16, height: 16, borderRadius: '50%', background: '#fff', transition: 'left 0.2s', boxShadow: '0 1px 3px rgba(0,0,0,0.2)' }} />
                  </div>
                  <span style={{ fontWeight: value ? 600 : 400, color: value ? 'var(--ink)' : 'var(--ink-3)' }}>{label}</span>
                </label>
              ))}
            </div>
          </div>
        </div>

        {/* Live preview panel */}
        <div className="card" style={{ padding: '20px 18px', position: 'sticky', top: 20 }}>
          <div className="card-title" style={{ marginBottom: 16 }}>Live Preview</div>

          <div style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: 8, padding: '28px', fontFamily: 'Inter, sans-serif' }}>
            <div style={{ borderBottom: `2px solid ${color}`, paddingBottom: 16, marginBottom: 20, display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                <div style={{ width: 44, height: 44, borderRadius: 9, overflow: 'hidden', flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', background: logo ? 'transparent' : `linear-gradient(135deg, ${color}, ${color}cc)` }}>
                  {logo ? <img src={logo} alt="Logo" style={{ width: '100%', height: '100%', objectFit: 'contain' }} /> : <span style={{ color: '#fff', fontWeight: 700, fontSize: 16 }}>{initials}</span>}
                </div>
                <div>
                  <div style={{ fontSize: 18, fontWeight: 800, color: '#0f172a' }}>{companyName}</div>
                  <div style={{ fontSize: 10, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.08em' }}>{tagline}</div>
                </div>
              </div>
              <div style={{ textAlign: 'right', fontSize: 11, color: '#64748b' }}>
                <div>Period: {new Date().toLocaleString('default', { month: 'long', year: 'numeric' })}</div>
                <div>Generated: {new Date().toLocaleDateString()}</div>
              </div>
            </div>

            <div style={{ fontSize: 14, fontWeight: 700, textAlign: 'center', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 18, color: '#1a1f2e' }}>
              Sample Document
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 20, background: '#f8fafc', padding: 14, borderRadius: 8 }}>
              <div>
                <div style={{ fontSize: 9, color: '#64748b', textTransform: 'uppercase', fontWeight: 700 }}>Employee</div>
                <div style={{ fontWeight: 600, fontSize: 13 }}>Jane Smith</div>
              </div>
              <div>
                <div style={{ fontSize: 9, color: '#64748b', textTransform: 'uppercase', fontWeight: 700 }}>Net Pay</div>
                <div style={{ fontWeight: 700, fontSize: 16, color: '#10b981' }}>$2,500</div>
              </div>
            </div>

            <div style={{ display: 'flex', justifyContent: 'space-between', borderTop: '1px solid #e2e8f0', paddingTop: 14, marginTop: 20 }}>
              <div style={{ width: '42%' }}>
                <div style={{ borderTop: `1px solid ${color}`, paddingTop: 8, fontSize: 11, color: '#475569' }}>
                  <strong>Finance Department</strong><br />{companyName} — Authorized Signature
                </div>
              </div>
              <div style={{ width: '42%', textAlign: 'right' }}>
                <div style={{ borderTop: '1px solid #cbd5e1', paddingTop: 8, fontSize: 11, color: '#475569' }}>
                  <strong>Employee Acknowledgement</strong><br />Jane Smith · Signature
                </div>
              </div>
            </div>

            {footerText && (
              <div style={{ marginTop: 16, fontSize: 9, color: '#94a3b8', borderTop: '1px solid #f1f5f9', paddingTop: 12, textAlign: 'center', lineHeight: 1.5 }}>
                {footerText}
              </div>
            )}
          </div>

          <div style={{ marginTop: 12, display: 'flex', gap: 6, flexWrap: 'wrap' }}>
            {applyPayslips && <span className="bdg bdg-acc">Payslips</span>}
            {applyContracts && <span className="bdg bdg-ok">Contracts</span>}
            {applyReports && <span className="bdg bdg-warn">Reports</span>}
          </div>
        </div>
      </div>
    </div>
  );
}
