'use client';

import { useState } from 'react';
import { dbOp } from '@/utils/db';

type ReportType = 'qa-evaluation' | 'warning' | 'collective-action' | 'performance-summary';

const REPORT_TYPES: { id: ReportType; label: string; desc: string }[] = [
  { id: 'qa-evaluation',      label: 'QA Evaluation',       desc: 'Quality Attributes score report from a coaching session' },
  { id: 'warning',            label: 'Written Warning',     desc: 'Formal disciplinary warning sent to employee inbox' },
  { id: 'collective-action',  label: 'Collective Action',   desc: 'Team-wide notice or policy enforcement memo' },
  { id: 'performance-summary',label: 'Performance Summary', desc: 'Monthly performance overview with attendance & sales data' },
];

const TYPE_BADGE: Record<string, string> = {
  'qa-evaluation': 'bdg bdg-acc',
  'warning': 'bdg bdg-err',
  'collective-action': 'bdg bdg-warn',
  'performance-summary': 'bdg bdg-ok',
};

function typeLabel(type: string) {
  return REPORT_TYPES.find(r => r.id === type)?.label ?? type;
}

function buildReportHtml(r: any, emp: any, supervisorName: string): string {
  const date = new Date(r.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const label = typeLabel(r.type);
  const nextReview = r.next_review
    ? `<div><span style="font-size:10px;color:#64748b;text-transform:uppercase;font-weight:700;display:block;margin-bottom:2px">Next Review</span><strong>${new Date(r.next_review).toLocaleDateString()}</strong></div>`
    : '';
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>${label}</title>
<style>body{font-family:Inter,Arial,sans-serif;max-width:800px;margin:40px auto;padding:0 40px;color:#1a1f2e;line-height:1.6}h2{font-size:16px;font-weight:700;text-align:center;text-transform:uppercase;letter-spacing:.5px;margin:0 0 24px}h3{font-size:13px;font-weight:700;border-bottom:1px solid #e4e7eb;padding-bottom:8px;margin:0 0 12px}p{font-size:13px;color:#4a5568;line-height:1.8;margin:0 0 20px;white-space:pre-wrap}@media print{body{margin:0}}</style>
</head><body>
<div style="display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #1a1f2e;padding-bottom:20px;margin-bottom:32px">
  <div><div style="font-size:22px;font-weight:800;color:#0f172a;letter-spacing:1px">PIONEERS VENEERS</div><div style="font-size:11px;color:#6b7689;text-transform:uppercase;letter-spacing:.08em;margin-top:4px">${label} · Official Document</div></div>
  <div style="text-align:right;font-size:12px;color:#64748b"><div>Date: ${date}</div><div>Ref: RPT-${r.id?.toString().slice(0,8).toUpperCase() ?? Date.now().toString().slice(-6)}</div></div>
</div>
<h2>${label}</h2>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:28px;background:#f8fafc;padding:18px;border-radius:8px;font-size:12px">
  <div><span style="font-size:10px;color:#64748b;text-transform:uppercase;font-weight:700;display:block;margin-bottom:2px">Employee</span><strong>${emp?.name ?? '—'}</strong></div>
  <div><span style="font-size:10px;color:#64748b;text-transform:uppercase;font-weight:700;display:block;margin-bottom:2px">Role</span><strong>${emp?.role ?? '—'}</strong></div>
  <div><span style="font-size:10px;color:#64748b;text-transform:uppercase;font-weight:700;display:block;margin-bottom:2px">Issued By</span><strong>${supervisorName}</strong></div>
  ${nextReview}
</div>
${r.notes ? `<div style="margin-bottom:24px"><h3>Notes &amp; Observations</h3><p>${r.notes}</p></div>` : ''}
${r.action_plan ? `<div style="margin-bottom:24px"><h3>Action Plan</h3><p>${r.action_plan}</p></div>` : ''}
<div style="margin-top:60px;display:flex;justify-content:space-between;border-top:1px solid #1a1f2e;padding-top:16px">
  <div style="width:40%"><strong style="font-size:12px">Issued By: ${supervisorName}</strong><br><span style="font-size:11px;color:#6b7689">Authorized Management Signature</span><div style="margin-top:36px;border-top:1px solid #94a3b8;font-size:10px;color:#94a3b8;padding-top:4px">Signature &amp; Date</div></div>
  <div style="width:40%;text-align:right"><strong style="font-size:12px">Employee Acknowledgement</strong><br><span style="font-size:11px;color:#6b7689">${emp?.name ?? ''}</span><div style="margin-top:8px;min-height:36px;font-family:'Dancing Script','Brush Script MT',cursive;font-size:28px;color:#1a1f2e"><!--EMP_SIG_PLACEHOLDER--></div><div style="margin-top:2px;border-top:1px solid #94a3b8;font-size:10px;color:#94a3b8;padding-top:4px"><!--EMP_DATE_PLACEHOLDER-->Signature &amp; Date</div></div>
</div>
<div style="margin-top:24px;font-size:9px;color:#94a3b8;text-align:center;border-top:1px solid #f1f5f9;padding-top:12px">Generated by Pioneers Veneers Enterprise Platform · ${date}</div>
</body></html>`;
}

function SendConfirm({ onConfirm, onCancel }: { onConfirm: () => void; onCancel: () => void }) {
  return (
    <div className="mb">
      <div className="md" style={{ width: 360 }}>
        <div className="md-t">Send to Inbox</div>
        <p style={{ fontSize: 13, color: 'var(--ink-2)', marginBottom: 20 }}>
          This will send the report to the employee's inbox. Are you sure?
        </p>
        <div style={{ display: 'flex', gap: 8 }}>
          <button className="btn btn-acc" onClick={onConfirm}>Send</button>
          <button className="btn btn-sec" onClick={onCancel}>Cancel</button>
        </div>
      </div>
    </div>
  );
}

export default function ReportsClient({
  reports: initialReports, sessions, employees, isMgmt, currentUserId, currentUserName,
}: {
  reports: any[];
  sessions: any[];
  employees: any[];
  isMgmt: boolean;
  currentUserId?: string;
  currentUserName: string;
}) {
  const [savedReports, setSavedReports] = useState<any[]>(initialReports);
  const [view, setView] = useState<'list' | 'create' | 'preview'>('list');
  const [reportType, setReportType] = useState<ReportType>('qa-evaluation');
  const [targetType, setTargetType] = useState<'individual' | 'team'>('individual');
  const [selectedEmployee, setSelectedEmployee] = useState('');
  const [selectedSession, setSelectedSession] = useState('');
  const [notes, setNotes] = useState('');
  const [printData, setPrintData] = useState<any>(null);
  const [sendTarget, setSendTarget] = useState<any>(null);
  const [sending, setSending] = useState(false);
  const [sentIds, setSentIds] = useState<Set<string>>(new Set());
  const [showPreviewSendConfirm, setShowPreviewSendConfirm] = useState(false);
  const [sendingPreview, setSendingPreview] = useState(false);
  const [previewSent, setPreviewSent] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [genError, setGenError] = useState('');

  const handleGenerate = async () => {
    setGenerating(true);
    setGenError('');
    const emp = employees.find(e => e.id === selectedEmployee);
    const session = sessions.find(s => s.id === selectedSession);
    const html = buildReportHtml(
      { id: Date.now(), created_at: new Date().toISOString(), type: reportType, notes, action_plan: session?.action_plan },
      emp ?? null,
      currentUserName,
    );

    const { data: saved, error } = await dbOp('reports', 'insert', {
      type: reportType,
      target_type: targetType,
      employee_id: emp?.id ?? null,
      employee_name: emp?.name ?? null,
      employee_role: emp?.role ?? null,
      notes: notes || null,
      session_id: session?.id ?? null,
      html_content: html,
      created_by: currentUserId ?? null,
      created_by_name: currentUserName,
    }, undefined, '*');

    if (error) {
      setGenError('Failed to save report. Please try again.');
      setGenerating(false);
      return;
    }

    const savedReport = saved?.[0];
    if (savedReport) setSavedReports(prev => [savedReport, ...prev]);

    setPrintData({
      type: reportType, targetType, employee: emp, session,
      notes, generatedBy: currentUserName,
      generatedAt: new Date().toLocaleDateString(),
      savedId: savedReport?.id, html,
    });
    setPreviewSent(false);
    setGenerating(false);
    setView('preview');
  };

  const sendPreviewToInbox = async () => {
    if (!printData?.employee?.id) return;
    setSendingPreview(true);
    const emp = printData.employee;
    const label = typeLabel(printData.type);
    const subject = `${label} — ${printData.generatedAt}`;
    const html = printData.html || buildReportHtml(
      { id: printData.savedId ?? Date.now(), created_at: new Date().toISOString(), type: printData.type, notes: printData.notes, action_plan: printData.session?.action_plan },
      emp, printData.generatedBy,
    );
    await dbOp('inbox_documents', 'insert', {
      user_id: emp.id,
      title: subject, subject,
      content: printData.notes || 'Please review the attached report.',
      type: 'Report',
      sender: printData.generatedBy,
      submitted_by_name: printData.generatedBy,
      approval_status: 'pending',
      requires_signature: true,
      is_read: false,
      html_content: html,
      doc_ref_type: 'report',
      doc_ref_id: printData.savedId ? String(printData.savedId) : undefined,
    });
    setSendingPreview(false);
    setShowPreviewSendConfirm(false);
    setPreviewSent(true);
  };

  const sendReportToInbox = async (r: any) => {
    setSending(true);
    if (r.employee_id) {
      const label = typeLabel(r.type);
      const subject = `${label} — ${new Date(r.created_at).toLocaleDateString()}`;
      await dbOp('inbox_documents', 'insert', {
        user_id: r.employee_id,
        title: subject, subject,
        content: r.notes ?? 'Please review the attached report.',
        type: 'Report',
        sender: r.created_by_name,
        submitted_by_name: r.created_by_name,
        approval_status: 'pending',
        requires_signature: true,
        is_read: false,
        html_content: r.html_content || '',
        doc_ref_type: 'report',
        doc_ref_id: String(r.id),
      });
      setSentIds(prev => new Set([...prev, r.id]));
    }
    setSendTarget(null);
    setSending(false);
  };

  // ── Preview ──────────────────────────────────────────────────────────────
  if (view === 'preview' && printData) {
    return (
      <div>
        <style dangerouslySetInnerHTML={{ __html: `
          @media print {
            .sb, .tb, .foot, .no-print, .pv-grid > aside { display: none !important; }
            .pv-grid { display: block !important; }
            .main, .cnt { padding: 0 !important; margin: 0 !important; }
            body { background: white !important; }
          }
        ` }} />
        <div className="no-print" style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}>
          <button className="btn btn-sec btn-sm" onClick={() => setView('list')}>← Back to Library</button>
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            {printData.employee?.id
              ? previewSent
                ? <span className="bdg bdg-ok">Sent to inbox</span>
                : <button className="btn btn-sec btn-sm" onClick={() => setShowPreviewSendConfirm(true)} disabled={sendingPreview}>
                    📤 Send to Inbox
                  </button>
              : null
            }
            <button className="btn btn-acc btn-sm" onClick={() => window.print()}>🖨 Print / Download PDF</button>
          </div>
        </div>
        {showPreviewSendConfirm && (
          <SendConfirm onConfirm={sendPreviewToInbox} onCancel={() => setShowPreviewSendConfirm(false)} />
        )}

        <div style={{ background: '#fff', padding: '48px', maxWidth: '800px', margin: '0 auto', boxShadow: 'var(--sh-2)', borderRadius: 8, border: '1px solid var(--line)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '2px solid var(--ink)', paddingBottom: 20, marginBottom: 32 }}>
            <div>
              <div style={{ fontSize: 22, fontWeight: 800, color: 'var(--ink)', letterSpacing: 1 }}>PIONEERS VENEERS</div>
              <div style={{ fontSize: 11, color: 'var(--ink-3)', textTransform: 'uppercase', letterSpacing: '0.08em', marginTop: 4 }}>
                {typeLabel(printData.type)} · Official Document
              </div>
            </div>
            <div style={{ textAlign: 'right', fontSize: 12, color: 'var(--ink-3)' }}>
              <div>Date: {printData.generatedAt}</div>
              <div>Ref: RPT-{printData.savedId?.toString().slice(0,8).toUpperCase() ?? Date.now().toString().slice(-6)}</div>
            </div>
          </div>

          <h2 style={{ fontSize: 16, fontWeight: 700, marginBottom: 24, textAlign: 'center', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
            {typeLabel(printData.type)}
          </h2>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 28, background: 'var(--surface-2)', padding: 18, borderRadius: 8 }}>
            {printData.targetType === 'individual' ? (
              <>
                <div><div style={{ fontSize: 10, color: 'var(--ink-3)', textTransform: 'uppercase', fontWeight: 600 }}>Employee</div><div style={{ fontWeight: 600 }}>{printData.employee?.name ?? 'All Employees'}</div></div>
                <div><div style={{ fontSize: 10, color: 'var(--ink-3)', textTransform: 'uppercase', fontWeight: 600 }}>Role</div><div style={{ fontWeight: 600 }}>{printData.employee?.role ?? '—'}</div></div>
                <div><div style={{ fontSize: 10, color: 'var(--ink-3)', textTransform: 'uppercase', fontWeight: 600 }}>Issued By</div><div style={{ fontWeight: 600 }}>{printData.generatedBy}</div></div>
              </>
            ) : (
              <>
                <div><div style={{ fontSize: 10, color: 'var(--ink-3)', textTransform: 'uppercase', fontWeight: 600 }}>Scope</div><div style={{ fontWeight: 600 }}>All Team Members</div></div>
                <div><div style={{ fontSize: 10, color: 'var(--ink-3)', textTransform: 'uppercase', fontWeight: 600 }}>Issued By</div><div style={{ fontWeight: 600 }}>{printData.generatedBy}</div></div>
              </>
            )}
          </div>

          {printData.type === 'qa-evaluation' && printData.session && (
            <div style={{ marginBottom: 24 }}>
              <h3 style={{ fontSize: 13, fontWeight: 700, borderBottom: '1px solid var(--line)', paddingBottom: 8, marginBottom: 12 }}>QA Session Details</h3>
              <div style={{ fontSize: 13, color: 'var(--ink-2)', lineHeight: 1.8 }}>
                <div><strong>Session Type:</strong> {printData.session.type}</div>
                {printData.session.notes && <div><strong>Notes:</strong> {printData.session.notes}</div>}
                {printData.session.action_plan && <div><strong>Action Plan:</strong> {printData.session.action_plan}</div>}
              </div>
            </div>
          )}

          <div style={{ marginBottom: 40 }}>
            <h3 style={{ fontSize: 13, fontWeight: 700, borderBottom: '1px solid var(--line)', paddingBottom: 8, marginBottom: 12 }}>
              {printData.type === 'warning' ? 'Warning Details' : printData.type === 'collective-action' ? 'Notice' : 'Notes & Observations'}
            </h3>
            <div style={{ fontSize: 13, color: 'var(--ink)', lineHeight: 1.8, whiteSpace: 'pre-wrap' }}>
              {printData.notes || 'No additional notes provided.'}
            </div>
          </div>

          <div style={{ marginTop: 60, display: 'flex', justifyContent: 'space-between' }}>
            <div style={{ width: '40%', borderTop: '1px solid var(--ink)', paddingTop: 10 }}>
              <strong style={{ fontSize: 12 }}>Issued By: {printData.generatedBy}</strong><br />
              <span style={{ fontSize: 11, color: 'var(--ink-3)' }}>Authorized Management Signature</span>
            </div>
            {printData.targetType === 'individual' && (
              <div style={{ width: '40%', borderTop: '1px solid var(--ink)', paddingTop: 10 }}>
                <strong style={{ fontSize: 12 }}>Employee Acknowledgement</strong><br />
                <span style={{ fontSize: 11, color: 'var(--ink-3)' }}>{printData.employee?.name} · Signature</span>
              </div>
            )}
          </div>

          <div style={{ marginTop: 32, textAlign: 'center', fontSize: 10, color: 'var(--ink-4)', borderTop: '1px solid var(--line-2)', paddingTop: 16 }}>
            This document was auto-generated by the Pioneers Veneers Enterprise Platform. It is legally binding upon physical signature.
          </div>
        </div>
      </div>
    );
  }

  // ── Create ───────────────────────────────────────────────────────────────
  if (view === 'create' && isMgmt) {
    const selectedTypeInfo = REPORT_TYPES.find(r => r.id === reportType);
    return (
      <div className="page-fade">
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}>
          <button className="btn btn-sec btn-sm" onClick={() => setView('list')}>← Back to Library</button>
        </div>

        <div className="card" style={{ maxWidth: 620 }}>
          <div className="card-hdr">
            <div className="card-title">Generate New Report</div>
          </div>
          <div className="card-body">
            <div className="pv-fld">
              <label>Report Type</label>
              <select value={reportType} onChange={e => setReportType(e.target.value as ReportType)}>
                {REPORT_TYPES.map(t => <option key={t.id} value={t.id}>{t.label}</option>)}
              </select>
              <div style={{ fontSize: 11, color: 'var(--ink-3)', marginTop: 4 }}>{selectedTypeInfo?.desc}</div>
            </div>

            <div className="pv-fld">
              <label>Target</label>
              <div style={{ display: 'flex', gap: 8 }}>
                <button type="button" className={`btn btn-sm ${targetType === 'individual' ? 'btn-acc' : 'btn-sec'}`} onClick={() => setTargetType('individual')}>Individual Employee</button>
                <button type="button" className={`btn btn-sm ${targetType === 'team' ? 'btn-acc' : 'btn-sec'}`} onClick={() => setTargetType('team')}>Whole Team</button>
              </div>
            </div>

            {targetType === 'individual' && (
              <div className="pv-fld">
                <label>Select Employee</label>
                <select value={selectedEmployee} onChange={e => setSelectedEmployee(e.target.value)} required>
                  <option value="">— Choose employee —</option>
                  {employees.map(e => <option key={e.id} value={e.id}>{e.name} ({e.role})</option>)}
                </select>
              </div>
            )}

            {reportType === 'qa-evaluation' && (
              <div className="pv-fld">
                <label>Coaching Session</label>
                <select value={selectedSession} onChange={e => setSelectedSession(e.target.value)}>
                  <option value="">— Link to a session (optional) —</option>
                  {sessions
                    .filter(s => !selectedEmployee || s.agent_id === selectedEmployee)
                    .map(s => (
                      <option key={s.id} value={s.id}>
                        {s.agent?.name} · {s.type} · {new Date(s.created_at ?? Date.now()).toLocaleDateString()}
                      </option>
                    ))
                  }
                </select>
              </div>
            )}

            <div className="pv-fld">
              <label>
                {reportType === 'warning' ? 'Warning Details & Reason' :
                 reportType === 'collective-action' ? 'Notice Content' :
                 reportType === 'performance-summary' ? 'Summary Notes' : 'Additional Notes'}
              </label>
              <textarea
                rows={5}
                value={notes}
                onChange={e => setNotes(e.target.value)}
                placeholder={
                  reportType === 'warning' ? 'Describe the policy violation, incident details, and expected corrective action...' :
                  reportType === 'collective-action' ? 'Write the team-wide notice or collective policy memo...' :
                  'Add observations, context, or manager commentary...'
                }
                style={{ resize: 'vertical' }}
              />
            </div>

            {genError && <div style={{ fontSize: 12, color: 'var(--err)', marginBottom: 12 }}>{genError}</div>}

            <button
              className="btn btn-acc"
              onClick={handleGenerate}
              disabled={generating || (targetType === 'individual' && !selectedEmployee)}
            >
              {generating ? 'Saving…' : 'Generate & Save Report →'}
            </button>
          </div>
        </div>
      </div>
    );
  }

  // ── Library ──────────────────────────────────────────────────────────────
  return (
    <div className="page-fade">
      <div className="stat-grid" style={{ marginBottom: 20 }}>
        <div className="stat-card" style={{ cursor: 'default' }}>
          <div className="stat-h"><div className="stat-ico ind">📊</div></div>
          <div className="stat-l">TOTAL REPORTS</div>
          <div className="stat-v">{savedReports.length}</div>
          <div className="stat-foot">Saved in library</div>
        </div>
        <div className="stat-card" style={{ cursor: 'default' }}>
          <div className="stat-h"><div className="stat-ico wn">⚠</div></div>
          <div className="stat-l">WARNINGS</div>
          <div className="stat-v">{savedReports.filter(r => r.type === 'warning').length}</div>
          <div className="stat-foot">Formal notices issued</div>
        </div>
        <div className="stat-card" style={{ cursor: 'default' }}>
          <div className="stat-h"><div className="stat-ico ok">✓</div></div>
          <div className="stat-l">QA EVALS</div>
          <div className="stat-v">{savedReports.filter(r => r.type === 'qa-evaluation').length}</div>
          <div className="stat-foot">Coaching & quality sessions</div>
        </div>
        <div className="stat-card" style={{ cursor: 'default' }}>
          <div className="stat-h"><div className="stat-ico ind">📤</div></div>
          <div className="stat-l">SENT TO INBOX</div>
          <div className="stat-v">{sentIds.size}</div>
          <div className="stat-foot">This session</div>
        </div>
      </div>

      <div className="card" style={{ overflow: 'hidden' }}>
        <div className="card-hdr">
          <div>
            <div className="card-title">Report Library</div>
            <div className="card-sub">All reports shared across management</div>
          </div>
          {isMgmt && (
            <button
              className="btn btn-acc btn-sm"
              onClick={() => { setView('create'); setNotes(''); setSelectedEmployee(''); setSelectedSession(''); setGenError(''); }}
            >
              + Generate Report
            </button>
          )}
        </div>

        {savedReports.length === 0 ? (
          <div style={{ padding: '40px 20px', textAlign: 'center', color: 'var(--ink-4)', fontSize: 13 }}>
            No reports yet. {isMgmt && 'Use "Generate Report" to create the first one.'}
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table className="tbl">
              <thead>
                <tr>
                  <th>Report</th>
                  <th>Type</th>
                  <th>Employee</th>
                  <th>Created By</th>
                  <th>Date</th>
                  <th style={{ textAlign: 'right' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {savedReports.map(r => (
                  <tr key={r.id}>
                    <td>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                        <div style={{ width: 32, height: 32, borderRadius: 8, background: 'var(--accent-soft)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 14, flexShrink: 0 }}>📊</div>
                        <div>
                          <div style={{ fontWeight: 500, fontSize: 13 }}>{r.employee_name || 'Whole Team'} — {typeLabel(r.type)}</div>
                          <div style={{ fontSize: 11, color: 'var(--ink-3)' }}>By {r.created_by_name}</div>
                        </div>
                      </div>
                    </td>
                    <td><span className={TYPE_BADGE[r.type] ?? 'bdg bdg-gy'}>{typeLabel(r.type)}</span></td>
                    <td style={{ color: 'var(--ink-3)', fontSize: 12 }}>{r.employee_name ?? 'Team'}</td>
                    <td style={{ color: 'var(--ink-3)', fontSize: 12 }}>{r.created_by_name ?? '—'}</td>
                    <td style={{ fontFamily: 'var(--mono)', fontSize: 11.5, color: 'var(--ink-3)' }}>{new Date(r.created_at).toLocaleDateString()}</td>
                    <td>
                      <div style={{ display: 'flex', gap: 6, justifyContent: 'flex-end' }}>
                        <button
                          className="btn btn-sec btn-sm"
                          onClick={() => {
                            setPreviewSent(false);
                            setPrintData({
                              type: r.type,
                              targetType: r.target_type,
                              employee: r.employee_id ? { id: r.employee_id, name: r.employee_name, role: r.employee_role } : null,
                              session: null,
                              notes: r.notes,
                              generatedBy: r.created_by_name,
                              generatedAt: new Date(r.created_at).toLocaleDateString(),
                              savedId: r.id,
                              html: r.html_content,
                            });
                            setView('preview');
                          }}
                        >Open</button>
                        {isMgmt && r.employee_id && !sentIds.has(r.id) && (
                          <button className="btn btn-sec btn-sm" onClick={() => setSendTarget(r)}>
                            Send to Inbox
                          </button>
                        )}
                        {sentIds.has(r.id) && <span className="bdg bdg-ok">Sent</span>}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {sendTarget && (
        <SendConfirm
          onConfirm={() => sendReportToInbox(sendTarget)}
          onCancel={() => setSendTarget(null)}
        />
      )}
    </div>
  );
}
